trigger:
  branches:
    include:
      - main

pool:
  name: Comp367_SH_Agent

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)'
  commitShort: $[substring(variables['Build.SourceVersion'], 0, 8)]
  baseVersion: '1.0.1'
steps:

- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build solution'

- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'Run tests'

- task: PowerShell@2
  displayName: 'Set Package Version'
  inputs:
    targetType: 'inline'
    script: |
      $baseVersion = "$(baseVersion)"
      $shortCommit = "$(commitShort)"
      $packageVersion = "$baseVersion-$shortCommit"
      Write-Host "##vso[task.setvariable variable=PackageVersion]$packageVersion"
      Write-Host "PackageVersion: $packageVersion"

- script: |
    dotnet pack StringUtility/StringUtility.csproj --configuration $(buildConfiguration) --no-build --output $(outputDir) /p:PackageVersion=$(PackageVersion)
  displayName: 'Pack NuGet package'

- task: NuGetToolInstaller@1                           
  displayName: 'NuGet Tool Installer'

- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- script: |
      nuget.exe push -Source "https://pkgs.dev.azure.com/rombao/Comp367Lab4/_packaging/string-utils-lab4-v2-feed/nuget/v3/index.json" -ApiKey az $(Build.ArtifactStagingDirectory)\*.nupkg
  displayName: Push